// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: party_service.proto

package partypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPartyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the party to retrieve.
	Name          *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartyRequest) Reset() {
	*x = GetPartyRequest{}
	mi := &file_party_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartyRequest) ProtoMessage() {}

func (x *GetPartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartyRequest.ProtoReflect.Descriptor instead.
func (*GetPartyRequest) Descriptor() ([]byte, []int) {
	return file_party_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPartyRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ListPartiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartiesRequest) Reset() {
	*x = ListPartiesRequest{}
	mi := &file_party_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartiesRequest) ProtoMessage() {}

func (x *ListPartiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartiesRequest.ProtoReflect.Descriptor instead.
func (*ListPartiesRequest) Descriptor() ([]byte, []int) {
	return file_party_service_proto_rawDescGZIP(), []int{1}
}

type ListPartiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parties.
	Parties       []*Party `protobuf:"bytes,1,rep,name=parties" json:"parties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartiesResponse) Reset() {
	*x = ListPartiesResponse{}
	mi := &file_party_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartiesResponse) ProtoMessage() {}

func (x *ListPartiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_party_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartiesResponse.ProtoReflect.Descriptor instead.
func (*ListPartiesResponse) Descriptor() ([]byte, []int) {
	return file_party_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListPartiesResponse) GetParties() []*Party {
	if x != nil {
		return x.Parties
	}
	return nil
}

type CreatePartyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The party to create. The name field will be ignored/overwritten.
	Party         *Party `protobuf:"bytes,1,opt,name=party" json:"party,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartyRequest) Reset() {
	*x = CreatePartyRequest{}
	mi := &file_party_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartyRequest) ProtoMessage() {}

func (x *CreatePartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartyRequest.ProtoReflect.Descriptor instead.
func (*CreatePartyRequest) Descriptor() ([]byte, []int) {
	return file_party_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePartyRequest) GetParty() *Party {
	if x != nil {
		return x.Party
	}
	return nil
}

type UpdatePartyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The party to update.
	Party         *Party `protobuf:"bytes,1,opt,name=party" json:"party,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePartyRequest) Reset() {
	*x = UpdatePartyRequest{}
	mi := &file_party_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartyRequest) ProtoMessage() {}

func (x *UpdatePartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePartyRequest) Descriptor() ([]byte, []int) {
	return file_party_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePartyRequest) GetParty() *Party {
	if x != nil {
		return x.Party
	}
	return nil
}

type DeletePartyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the party to delete.
	Name          *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePartyRequest) Reset() {
	*x = DeletePartyRequest{}
	mi := &file_party_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePartyRequest) ProtoMessage() {}

func (x *DeletePartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_party_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePartyRequest.ProtoReflect.Descriptor instead.
func (*DeletePartyRequest) Descriptor() ([]byte, []int) {
	return file_party_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePartyRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_party_service_proto protoreflect.FileDescriptor

const file_party_service_proto_rawDesc = "" +
	"\n" +
	"\x13party_service.proto\x12\x0fgetting_married\x1a\vparty.proto\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\x0fGetPartyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x14\n" +
	"\x12ListPartiesRequest\"G\n" +
	"\x13ListPartiesResponse\x120\n" +
	"\aparties\x18\x01 \x03(\v2\x16.getting_married.PartyR\aparties\"B\n" +
	"\x12CreatePartyRequest\x12,\n" +
	"\x05party\x18\x01 \x01(\v2\x16.getting_married.PartyR\x05party\"B\n" +
	"\x12UpdatePartyRequest\x12,\n" +
	"\x05party\x18\x01 \x01(\v2\x16.getting_married.PartyR\x05party\"(\n" +
	"\x12DeletePartyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\x9c\x03\n" +
	"\fPartyService\x12F\n" +
	"\bGetParty\x12 .getting_married.GetPartyRequest\x1a\x16.getting_married.Party\"\x00\x12Z\n" +
	"\vListParties\x12#.getting_married.ListPartiesRequest\x1a$.getting_married.ListPartiesResponse\"\x00\x12L\n" +
	"\vCreateParty\x12#.getting_married.CreatePartyRequest\x1a\x16.getting_married.Party\"\x00\x12L\n" +
	"\vUpdateParty\x12#.getting_married.UpdatePartyRequest\x1a\x16.getting_married.Party\"\x00\x12L\n" +
	"\vDeleteParty\x12#.getting_married.DeletePartyRequest\x1a\x16.google.protobuf.Empty\"\x00B.Z,github.com/sbarfurth/getting-married/partypbb\beditionsp\xe8\a"

var (
	file_party_service_proto_rawDescOnce sync.Once
	file_party_service_proto_rawDescData []byte
)

func file_party_service_proto_rawDescGZIP() []byte {
	file_party_service_proto_rawDescOnce.Do(func() {
		file_party_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_party_service_proto_rawDesc), len(file_party_service_proto_rawDesc)))
	})
	return file_party_service_proto_rawDescData
}

var file_party_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_party_service_proto_goTypes = []any{
	(*GetPartyRequest)(nil),     // 0: getting_married.GetPartyRequest
	(*ListPartiesRequest)(nil),  // 1: getting_married.ListPartiesRequest
	(*ListPartiesResponse)(nil), // 2: getting_married.ListPartiesResponse
	(*CreatePartyRequest)(nil),  // 3: getting_married.CreatePartyRequest
	(*UpdatePartyRequest)(nil),  // 4: getting_married.UpdatePartyRequest
	(*DeletePartyRequest)(nil),  // 5: getting_married.DeletePartyRequest
	(*Party)(nil),               // 6: getting_married.Party
	(*emptypb.Empty)(nil),       // 7: google.protobuf.Empty
}
var file_party_service_proto_depIdxs = []int32{
	6, // 0: getting_married.ListPartiesResponse.parties:type_name -> getting_married.Party
	6, // 1: getting_married.CreatePartyRequest.party:type_name -> getting_married.Party
	6, // 2: getting_married.UpdatePartyRequest.party:type_name -> getting_married.Party
	0, // 3: getting_married.PartyService.GetParty:input_type -> getting_married.GetPartyRequest
	1, // 4: getting_married.PartyService.ListParties:input_type -> getting_married.ListPartiesRequest
	3, // 5: getting_married.PartyService.CreateParty:input_type -> getting_married.CreatePartyRequest
	4, // 6: getting_married.PartyService.UpdateParty:input_type -> getting_married.UpdatePartyRequest
	5, // 7: getting_married.PartyService.DeleteParty:input_type -> getting_married.DeletePartyRequest
	6, // 8: getting_married.PartyService.GetParty:output_type -> getting_married.Party
	2, // 9: getting_married.PartyService.ListParties:output_type -> getting_married.ListPartiesResponse
	6, // 10: getting_married.PartyService.CreateParty:output_type -> getting_married.Party
	6, // 11: getting_married.PartyService.UpdateParty:output_type -> getting_married.Party
	7, // 12: getting_married.PartyService.DeleteParty:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_party_service_proto_init() }
func file_party_service_proto_init() {
	if File_party_service_proto != nil {
		return
	}
	file_party_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_party_service_proto_rawDesc), len(file_party_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_party_service_proto_goTypes,
		DependencyIndexes: file_party_service_proto_depIdxs,
		MessageInfos:      file_party_service_proto_msgTypes,
	}.Build()
	File_party_service_proto = out.File
	file_party_service_proto_goTypes = nil
	file_party_service_proto_depIdxs = nil
}
