// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: party.proto

package partypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RSVP_Response int32

const (
	RSVP_UNSPECIFIED RSVP_Response = 0
	RSVP_ACCEPTED    RSVP_Response = 1
	RSVP_DECLINED    RSVP_Response = 2
)

// Enum value maps for RSVP_Response.
var (
	RSVP_Response_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ACCEPTED",
		2: "DECLINED",
	}
	RSVP_Response_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ACCEPTED":    1,
		"DECLINED":    2,
	}
)

func (x RSVP_Response) Enum() *RSVP_Response {
	p := new(RSVP_Response)
	*p = x
	return p
}

func (x RSVP_Response) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RSVP_Response) Descriptor() protoreflect.EnumDescriptor {
	return file_party_proto_enumTypes[0].Descriptor()
}

func (RSVP_Response) Type() protoreflect.EnumType {
	return &file_party_proto_enumTypes[0]
}

func (x RSVP_Response) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type RSVP struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Response            RSVP_Response          `protobuf:"varint,3,opt,name=response,enum=getting_married.RSVP_Response"`
	xxx_hidden_DietaryRestrictions *string                `protobuf:"bytes,4,opt,name=dietary_restrictions,json=dietaryRestrictions"`
	xxx_hidden_MusicWishes         *string                `protobuf:"bytes,5,opt,name=music_wishes,json=musicWishes"`
	xxx_hidden_Note                *string                `protobuf:"bytes,6,opt,name=note"`
	xxx_hidden_UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *RSVP) Reset() {
	*x = RSVP{}
	mi := &file_party_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSVP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSVP) ProtoMessage() {}

func (x *RSVP) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RSVP) GetResponse() RSVP_Response {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Response
		}
	}
	return RSVP_UNSPECIFIED
}

func (x *RSVP) GetDietaryRestrictions() string {
	if x != nil {
		if x.xxx_hidden_DietaryRestrictions != nil {
			return *x.xxx_hidden_DietaryRestrictions
		}
		return ""
	}
	return ""
}

func (x *RSVP) GetMusicWishes() string {
	if x != nil {
		if x.xxx_hidden_MusicWishes != nil {
			return *x.xxx_hidden_MusicWishes
		}
		return ""
	}
	return ""
}

func (x *RSVP) GetNote() string {
	if x != nil {
		if x.xxx_hidden_Note != nil {
			return *x.xxx_hidden_Note
		}
		return ""
	}
	return ""
}

func (x *RSVP) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *RSVP) SetResponse(v RSVP_Response) {
	x.xxx_hidden_Response = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *RSVP) SetDietaryRestrictions(v string) {
	x.xxx_hidden_DietaryRestrictions = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *RSVP) SetMusicWishes(v string) {
	x.xxx_hidden_MusicWishes = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *RSVP) SetNote(v string) {
	x.xxx_hidden_Note = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *RSVP) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *RSVP) HasResponse() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RSVP) HasDietaryRestrictions() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RSVP) HasMusicWishes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RSVP) HasNote() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RSVP) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *RSVP) ClearResponse() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Response = RSVP_UNSPECIFIED
}

func (x *RSVP) ClearDietaryRestrictions() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DietaryRestrictions = nil
}

func (x *RSVP) ClearMusicWishes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MusicWishes = nil
}

func (x *RSVP) ClearNote() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Note = nil
}

func (x *RSVP) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type RSVP_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Response            *RSVP_Response
	DietaryRestrictions *string
	MusicWishes         *string
	Note                *string
	UpdatedAt           *timestamppb.Timestamp
}

func (b0 RSVP_builder) Build() *RSVP {
	m0 := &RSVP{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Response != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Response = *b.Response
	}
	if b.DietaryRestrictions != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_DietaryRestrictions = b.DietaryRestrictions
	}
	if b.MusicWishes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_MusicWishes = b.MusicWishes
	}
	if b.Note != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Note = b.Note
	}
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type Guest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FirstName   *string                `protobuf:"bytes,1,opt,name=first_name,json=firstName"`
	xxx_hidden_LastName    *string                `protobuf:"bytes,2,opt,name=last_name,json=lastName"`
	xxx_hidden_Rsvp        *RSVP                  `protobuf:"bytes,3,opt,name=rsvp"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Guest) Reset() {
	*x = Guest{}
	mi := &file_party_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guest) ProtoMessage() {}

func (x *Guest) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Guest) GetFirstName() string {
	if x != nil {
		if x.xxx_hidden_FirstName != nil {
			return *x.xxx_hidden_FirstName
		}
		return ""
	}
	return ""
}

func (x *Guest) GetLastName() string {
	if x != nil {
		if x.xxx_hidden_LastName != nil {
			return *x.xxx_hidden_LastName
		}
		return ""
	}
	return ""
}

func (x *Guest) GetRsvp() *RSVP {
	if x != nil {
		return x.xxx_hidden_Rsvp
	}
	return nil
}

func (x *Guest) SetFirstName(v string) {
	x.xxx_hidden_FirstName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Guest) SetLastName(v string) {
	x.xxx_hidden_LastName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Guest) SetRsvp(v *RSVP) {
	x.xxx_hidden_Rsvp = v
}

func (x *Guest) HasFirstName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Guest) HasLastName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Guest) HasRsvp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Rsvp != nil
}

func (x *Guest) ClearFirstName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FirstName = nil
}

func (x *Guest) ClearLastName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_LastName = nil
}

func (x *Guest) ClearRsvp() {
	x.xxx_hidden_Rsvp = nil
}

type Guest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FirstName *string
	LastName  *string
	Rsvp      *RSVP
}

func (b0 Guest_builder) Build() *Guest {
	m0 := &Guest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FirstName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_FirstName = b.FirstName
	}
	if b.LastName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_LastName = b.LastName
	}
	x.xxx_hidden_Rsvp = b.Rsvp
	return m0
}

// Party of guests that are invited to the wedding. Contact information is
// always managed at the Party rather than the guest level.
type Party struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_DisplayName *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName"`
	xxx_hidden_Manager     *Guest                 `protobuf:"bytes,3,opt,name=manager"`
	xxx_hidden_Guests      *[]*Guest              `protobuf:"bytes,4,rep,name=guests"`
	xxx_hidden_MaxGuests   int32                  `protobuf:"varint,5,opt,name=max_guests,json=maxGuests"`
	xxx_hidden_Address     *Party_Address         `protobuf:"bytes,6,opt,name=address"`
	xxx_hidden_Contact     *Party_Contact         `protobuf:"bytes,7,opt,name=contact"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Party) Reset() {
	*x = Party{}
	mi := &file_party_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Party) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Party) ProtoMessage() {}

func (x *Party) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Party) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Party) GetDisplayName() string {
	if x != nil {
		if x.xxx_hidden_DisplayName != nil {
			return *x.xxx_hidden_DisplayName
		}
		return ""
	}
	return ""
}

func (x *Party) GetManager() *Guest {
	if x != nil {
		return x.xxx_hidden_Manager
	}
	return nil
}

func (x *Party) GetGuests() []*Guest {
	if x != nil {
		if x.xxx_hidden_Guests != nil {
			return *x.xxx_hidden_Guests
		}
	}
	return nil
}

func (x *Party) GetMaxGuests() int32 {
	if x != nil {
		return x.xxx_hidden_MaxGuests
	}
	return 0
}

func (x *Party) GetAddress() *Party_Address {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return nil
}

func (x *Party) GetContact() *Party_Contact {
	if x != nil {
		return x.xxx_hidden_Contact
	}
	return nil
}

func (x *Party) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Party) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *Party) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *Party) SetManager(v *Guest) {
	x.xxx_hidden_Manager = v
}

func (x *Party) SetGuests(v []*Guest) {
	x.xxx_hidden_Guests = &v
}

func (x *Party) SetMaxGuests(v int32) {
	x.xxx_hidden_MaxGuests = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Party) SetAddress(v *Party_Address) {
	x.xxx_hidden_Address = v
}

func (x *Party) SetContact(v *Party_Contact) {
	x.xxx_hidden_Contact = v
}

func (x *Party) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Party) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Party) HasDisplayName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Party) HasManager() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Manager != nil
}

func (x *Party) HasMaxGuests() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Party) HasAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Address != nil
}

func (x *Party) HasContact() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Contact != nil
}

func (x *Party) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Party) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Party) ClearDisplayName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DisplayName = nil
}

func (x *Party) ClearManager() {
	x.xxx_hidden_Manager = nil
}

func (x *Party) ClearMaxGuests() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_MaxGuests = 0
}

func (x *Party) ClearAddress() {
	x.xxx_hidden_Address = nil
}

func (x *Party) ClearContact() {
	x.xxx_hidden_Contact = nil
}

func (x *Party) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type Party_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        *string
	DisplayName *string
	Manager     *Guest
	Guests      []*Guest
	// Maximum number of guests in this party, not including the party manager.
	MaxGuests *int32
	Address   *Party_Address
	Contact   *Party_Contact
	UpdatedAt *timestamppb.Timestamp
}

func (b0 Party_builder) Build() *Party {
	m0 := &Party{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Name = b.Name
	}
	if b.DisplayName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_DisplayName = b.DisplayName
	}
	x.xxx_hidden_Manager = b.Manager
	x.xxx_hidden_Guests = &b.Guests
	if b.MaxGuests != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_MaxGuests = *b.MaxGuests
	}
	x.xxx_hidden_Address = b.Address
	x.xxx_hidden_Contact = b.Contact
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type Party_Address struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Street      *string                `protobuf:"bytes,1,opt,name=street"`
	xxx_hidden_PostalCode  *string                `protobuf:"bytes,2,opt,name=postal_code,json=postalCode"`
	xxx_hidden_City        *string                `protobuf:"bytes,3,opt,name=city"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Party_Address) Reset() {
	*x = Party_Address{}
	mi := &file_party_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Party_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Party_Address) ProtoMessage() {}

func (x *Party_Address) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Party_Address) GetStreet() string {
	if x != nil {
		if x.xxx_hidden_Street != nil {
			return *x.xxx_hidden_Street
		}
		return ""
	}
	return ""
}

func (x *Party_Address) GetPostalCode() string {
	if x != nil {
		if x.xxx_hidden_PostalCode != nil {
			return *x.xxx_hidden_PostalCode
		}
		return ""
	}
	return ""
}

func (x *Party_Address) GetCity() string {
	if x != nil {
		if x.xxx_hidden_City != nil {
			return *x.xxx_hidden_City
		}
		return ""
	}
	return ""
}

func (x *Party_Address) SetStreet(v string) {
	x.xxx_hidden_Street = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Party_Address) SetPostalCode(v string) {
	x.xxx_hidden_PostalCode = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Party_Address) SetCity(v string) {
	x.xxx_hidden_City = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Party_Address) HasStreet() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Party_Address) HasPostalCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Party_Address) HasCity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Party_Address) ClearStreet() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Street = nil
}

func (x *Party_Address) ClearPostalCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PostalCode = nil
}

func (x *Party_Address) ClearCity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_City = nil
}

type Party_Address_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Street     *string
	PostalCode *string
	City       *string
}

func (b0 Party_Address_builder) Build() *Party_Address {
	m0 := &Party_Address{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Street != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Street = b.Street
	}
	if b.PostalCode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PostalCode = b.PostalCode
	}
	if b.City != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_City = b.City
	}
	return m0
}

type Party_Contact struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Email       *string                `protobuf:"bytes,1,opt,name=email"`
	xxx_hidden_Phone       *string                `protobuf:"bytes,2,opt,name=phone"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Party_Contact) Reset() {
	*x = Party_Contact{}
	mi := &file_party_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Party_Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Party_Contact) ProtoMessage() {}

func (x *Party_Contact) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Party_Contact) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *Party_Contact) GetPhone() string {
	if x != nil {
		if x.xxx_hidden_Phone != nil {
			return *x.xxx_hidden_Phone
		}
		return ""
	}
	return ""
}

func (x *Party_Contact) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Party_Contact) SetPhone(v string) {
	x.xxx_hidden_Phone = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Party_Contact) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Party_Contact) HasPhone() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Party_Contact) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Email = nil
}

func (x *Party_Contact) ClearPhone() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Phone = nil
}

type Party_Contact_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Email *string
	Phone *string
}

func (b0 Party_Contact_builder) Build() *Party_Contact {
	m0 := &Party_Contact{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Email = b.Email
	}
	if b.Phone != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Phone = b.Phone
	}
	return m0
}

var File_party_proto protoreflect.FileDescriptor

const file_party_proto_rawDesc = "" +
	"\n" +
	"\vparty.proto\x12\x0fgetting_married\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!google/protobuf/go_features.proto\"\xa0\x02\n" +
	"\x04RSVP\x12:\n" +
	"\bresponse\x18\x03 \x01(\x0e2\x1e.getting_married.RSVP.ResponseR\bresponse\x121\n" +
	"\x14dietary_restrictions\x18\x04 \x01(\tR\x13dietaryRestrictions\x12!\n" +
	"\fmusic_wishes\x18\x05 \x01(\tR\vmusicWishes\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"7\n" +
	"\bResponse\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\f\n" +
	"\bACCEPTED\x10\x01\x12\f\n" +
	"\bDECLINED\x10\x02\"n\n" +
	"\x05Guest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12)\n" +
	"\x04rsvp\x18\x03 \x01(\v2\x15.getting_married.RSVPR\x04rsvp\"\xfd\x03\n" +
	"\x05Party\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x120\n" +
	"\amanager\x18\x03 \x01(\v2\x16.getting_married.GuestR\amanager\x12.\n" +
	"\x06guests\x18\x04 \x03(\v2\x16.getting_married.GuestR\x06guests\x12\x1d\n" +
	"\n" +
	"max_guests\x18\x05 \x01(\x05R\tmaxGuests\x128\n" +
	"\aaddress\x18\x06 \x01(\v2\x1e.getting_married.Party.AddressR\aaddress\x128\n" +
	"\acontact\x18\a \x01(\v2\x1e.getting_married.Party.ContactR\acontact\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aV\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x1f\n" +
	"\vpostal_code\x18\x02 \x01(\tR\n" +
	"postalCode\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x1a5\n" +
	"\aContact\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phoneB6Z,github.com/sbarfurth/getting-married/partypb\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_party_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_party_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_party_proto_goTypes = []any{
	(RSVP_Response)(0),            // 0: getting_married.RSVP.Response
	(*RSVP)(nil),                  // 1: getting_married.RSVP
	(*Guest)(nil),                 // 2: getting_married.Guest
	(*Party)(nil),                 // 3: getting_married.Party
	(*Party_Address)(nil),         // 4: getting_married.Party.Address
	(*Party_Contact)(nil),         // 5: getting_married.Party.Contact
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_party_proto_depIdxs = []int32{
	0, // 0: getting_married.RSVP.response:type_name -> getting_married.RSVP.Response
	6, // 1: getting_married.RSVP.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: getting_married.Guest.rsvp:type_name -> getting_married.RSVP
	2, // 3: getting_married.Party.manager:type_name -> getting_married.Guest
	2, // 4: getting_married.Party.guests:type_name -> getting_married.Guest
	4, // 5: getting_married.Party.address:type_name -> getting_married.Party.Address
	5, // 6: getting_married.Party.contact:type_name -> getting_married.Party.Contact
	6, // 7: getting_married.Party.updated_at:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_party_proto_init() }
func file_party_proto_init() {
	if File_party_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_party_proto_rawDesc), len(file_party_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_party_proto_goTypes,
		DependencyIndexes: file_party_proto_depIdxs,
		EnumInfos:         file_party_proto_enumTypes,
		MessageInfos:      file_party_proto_msgTypes,
	}.Build()
	File_party_proto = out.File
	file_party_proto_goTypes = nil
	file_party_proto_depIdxs = nil
}
